### ISSUE TITLE
--set-version-string and --set-product-version doesn't work on Firefox's exe

### ISSUE THREAD

**Issue by duanyao** [electron/rcedit#10]
When I try to modify Firefox's exe with rcedit, I found that `--set-version-string` and `--set-product-version` doesn't work: instead of modifying version strings or production version, rcedit remove them (right click -> property shows empty fields for the modified exe).

Example command: `rcedit.exe "updater.exe" --set-version-string "Comments" "This is an exe"`.

I installed rcedit.exe via `npm install rcedit`, and downloaded Firefox binary here: http://archive.mozilla.org/pub/firefox/releases/45.0/win32/en-US/sdk/firefox-45.0.sdk.zip

**Comment by kevinsawicki** [comment]
Fixed by #26 and released in `0.6.0`.

**Comment by smbecker** [comment]
I don't think this is 100% fixed. It no longer clears everything out when setting the icon but it does still clear out any previous file description when only setting the icon.
