### ISSUE TITLE
Rcedit command not found

### ISSUE THREAD

**Issue by Mood-Singer** [electron/rcedit#22]
here is what i did
cloned that repositories 
ran that gyp command
 did that rcedit command to change the icon and 
here is what i get

"rcedit :command not found"

i didnt build the .sln file 
what do i do

**Comment by kevinsawicki** [comment]
> i didnt build the .sln file 

You need to build the `.sln` file or download `rcedit.exe` directly from https://github.com/electron/node-rcedit/blob/master/bin/rcedit.exe
