### ISSUE TITLE
Wrong version number?

### ISSUE THREAD

**Issue by beppe9000** [electron/rcedit#28]
When I do 

```
rcedit the.exe --set-file-version "1.2.6075.6043" --set-product-version "1.2.6075.6043"
```

 I get these sub numbers that are wrong:

```
FILEVERSION     1,2,187,155
PRODUCTVERSION  1,2,187,155
```

This is a .Net executable.
Is there a fix? Maybe the version numbers are too high?

**Comment by skyline75489** [comment]
I'm guessing you're also using the binary in `release`. There seems to be some kind of bug that truncates the version down to 4-bit. Fetch the code from master and compile your own binary and it should work.

**Comment by zcbenz** [comment]
Closing since it seems to work fine with the binaries produced on appveyor.
