### ISSUE TITLE
Change other fields like "CompanyName"

### ISSUE THREAD

**Issue by ThibaultFriedrich** [electron/rcedit#29]
Hi,

Rcedit works very well for me but is it possible to change the other fields in a executable like the CompanyName, the FileDescription or ProductName ?

**Comment by kevinsawicki** [comment]
@ThibaultFriedrich Yes, you can pass them into via the `version-string` object if you are using the node bindings or `rcedit "path-to-exe-or-dll" --set-version-string "FileDescription" "Hello"` if you are using the command line.
