### ISSUE TITLE
Another build

### ISSUE THREAD

**Issue by geek1011** [electron/rcedit#30]
I have a few questions
1. When will another release be made?
2. I do not use Visual Studio (I use SharpDevelop) and I would like a build of the current sources. 

Is this possible?

**Comment by kevinsawicki** [comment]
> When will another release be made?

The latest changes have been released in the node module that bundles this, https://github.com/electron/node-rcedit

>  I do not use Visual Studio (I use SharpDevelop) and I would like a build of the current sources.

You can download a prebuilt version of this from https://github.com/electron/node-rcedit/blob/master/bin/rcedit.exe
