### ISSUE TITLE
after set product version it also destroyed other fields 

### ISSUE THREAD

**Issue by ScottKaiGu** [electron/rcedit#32]
below fields were destroyed as well

Query [LegalTrademarks] error
Query [OriginalFilename] error
Query [PrivateBuild] error
Query [ProductName] error
Query [ProductVersion] error
Query [SpecialBuild] error

**Comment by RaptDept** [comment]
Were you using the last release posted here on a .NET executable? It's outdated, and this issue is supposed to be fixed by now. Try the more updated binary mentioned in https://github.com/electron/rcedit/issues/30#issuecomment-247379739 or build the latest source yourself.

**Comment by zcbenz** [comment]
Closing since it has been fixed.
