### ISSUE TITLE
rcedit for x64: Unable to change version string

### ISSUE THREAD

**Issue by fcharlie** [electron/rcedit#34]
When I build rcedit-win64, I use it change Exe file version string, 
It's report: **Unable to change version string**

But rcedit-x86 success.

Reson:
https://github.com/electron/rcedit/blob/1c9920ac153e6d4cd2d63ddb4148a323e4b94d2e/src/rescle.cc#L347
```c++
auto keySize = (wcslen(entry->szKey) + 1) * sizeof(WCHAR);
```

Visual Studio Report:  **Access violation reading location**

**Comment by russelh15** [comment]
Also having this same issue when trying to bump my version number from 3.9.0 to 4.0.0.

@fcharlie were you ever able to solve this? I'm on Windows 10 using Electron 1.4.3

**Comment by zcbenz** [comment]
Fixed with https://github.com/electron/rcedit/pull/55.
