### ISSUE TITLE
Fatal error: Unexpected trailing arguments

### ISSUE THREAD

**Issue by KaustubhPatange** [electron/rcedit#47]
I tried changing the resource string from RCEDIT 
`rcedit --set-resource-string 65201 "This is a test"`

It always says Unexpected trailing argument, also I tried same thing with .net exe and other machine language exe compiled through C++ or python, still the same thing. Also other functions like setting execution level is also not working. Can't figure out the solution. 

Any Help or Suggestion ! THANKS IN ADVANCE

**Comment by zcbenz** [comment]
The file path should be passed before passing the flags.

```
rcdit /path/to/exe --flags
```
