### ISSUE TITLE
Unable to set icon on an exe which doesn't have an icon currently set

### ISSUE THREAD

**Issue by thomasmfields** [electron/rcedit#57]
Hi there,

I can't seem to be able to change the icon on an exe that is using the Windows default exe icon. 

To repro the issue:

1) Open the rcedit solution file
2) Go to Project Properties->C/C++->Code Generation->Runtime Library and change it to "Multi threaded Debug /Mtd"
3) Build from source
4) Set debugging arguments to:

C:\some_path_to_exe\testexe.exe --set-icon "C:\some_path_to_icon\icon.ico"

Note how you get:

Debug Assertion Failed!

Program: C:\Users\gbfieldst\Downloads\rcedit-master\Default\rcedit.exe
File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtree
Line: 238

Expression: map/set iterator not dereferencable

Callstack:
>	rcedit.exe!std::_Debug_message(const wchar_t * message, const wchar_t * file, unsigned int line) Line 17	C++
 	rcedit.exe!std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned short const ,rescle::ResourceUpdater::IconResInfo> > > >::operator*() Line 239	C++
 	[Inline Frame] rcedit.exe!std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned short const ,rescle::ResourceUpdater::IconResInfo> > > >::operator*()	C++
 	[Inline Frame] rcedit.exe!std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned short const ,rescle::ResourceUpdater::IconResInfo> > > >::operator->()	C++
 	rcedit.exe!rescle::ResourceUpdater::SetIcon(const wchar_t * path) Line 640	C++
 	rcedit.exe!wmain(int argc, const wchar_t * * argv) Line 83	C++

This is because ResourceUpdater::SetIcon(const WCHAR* path) does:

 auto& langId = iconBundleMap.begin()->first;
  
but the map is empty!

The executable I used is attached. It's 01_vertex_program.exe from the NVIDIA Cg toolkit install.
[01_vertex_program.zip](https://github.com/electron/rcedit/files/1303666/01_vertex_program.zip)

Any ideas how this might be fixed?

Regards,
Tom

**Comment by malept** [comment]
I think this is the same as #56, although with more C++ debug info.

**Comment by thomasmfields** [comment]
Not sure. The copy of rcedit I have was downloaded on 9th Sept, which predates the commit mentioned in https://github.com/electron/rcedit/issues/56

**Comment by malept** [comment]
Could you make sure it's reproducible with the latest rcedit?

**Comment by thomasmfields** [comment]
With the latest rcedit I get:

Unable to set icon.

So that's good. So rcedit can only replace icons rather than add them? Is that correct?

**Comment by malept** [comment]
That's my understanding.

**Comment by thomasmfields** [comment]
OK. So I'm now hitting https://github.com/electron/rcedit/issues/56 which used to work prior to updating to latest.

**Comment by thomasmfields** [comment]
The fix for https://github.com/electron/rcedit/issues/56 has now caused this issue again.

**Comment by robi-wan** [comment]
I tried your example with [this artifact](https://ci.appveyor.com/project/electron-bot/rcedit/branch/master/job/9hwjfy8jj11wnyil/artifacts) - it worked.

Nevertheless there is a bug: accessing the key of the 'first' element of an empty map should be considered.

I just tried these changes:
```
diff --git a/src/rescle.cc b/src/rescle.cc
index 8ca6f60..a0779d2 100644
--- a/src/rescle.cc
+++ b/src/rescle.cc
@@ -606,12 +606,18 @@ bool ResourceUpdater::SetIcon(const WCHAR* path, const LANGID& langId,
 }

 bool ResourceUpdater::SetIcon(const WCHAR* path, const LANGID& langId) {
-  UINT iconBundle = iconBundleMap_[langId].iconBundles.begin()->first;
+  UINT iconBundle;
+  if (!iconBundleMap_[langId].iconBundles.empty()) {
+    iconBundle = iconBundleMap_[langId].iconBundles.begin()->first;
+  }
   return SetIcon(path, langId, iconBundle);
 }

 bool ResourceUpdater::SetIcon(const WCHAR* path) {
-  LANGID langId = iconBundleMap_.begin()->first;
+  LANGID langId;
+  if (!iconBundleMap_.empty()) {
+       langId = iconBundleMap_.begin()->first;
+  }
   return SetIcon(path, langId);
 }
```

They seem to work - I did not get Errors for your testcase (I did not test anything other.)

**Comment by robi-wan** [comment]
@thomasmfields Can you confirm that [this patch](https://github.com/electron/rcedit/issues/57#issuecomment-329862097) works?
Given a positive response I can prepare a Pull Request.

**Comment by thomasmfields** [comment]
Looks good to me.
