### ISSUE TITLE
Appveyor configuration problem?

### ISSUE THREAD

**Issue by GitMensch** [electron/rcedit#64]
The [console output](https://ci.appveyor.com/project/zcbenz/rcedit/branch/master/job/lbcqi4i2e4r9yqwo) shows:

~~~
Uploading artifacts...
[1/1] Default\rcedit-x64.exe (1,297,920 bytes)...100%
"GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
~~~

Is this a warning that should be fixed?

**Comment by malept** [comment]
This is something that AppVeyor will always do, unless it's running for a git tag.
