### ISSUE TITLE
Should I use 64-bit version or 32-bit version

### ISSUE THREAD

**Issue by JonathanMATechServices** [electron/rcedit#68]
How do I know if I should use the 64-bit (x64) or 32-bit (x86) version of the binary? Or does it matter as long as my OS is 64-bit?

**Comment by MarkTiedemann** [comment]
> How do I know if I should use the 64-bit (x64) or 32-bit (x86) version of the binary?

See https://ss64.com/nt/syntax-64bit.html for "_Detecting 64 bit vs 32 bit_".

```
C:\>echo %PROCESSOR_ARCHITECTURE%
AMD64

C:\>powershell [environment]::is64bitoperatingsystem
True

C:\>powershell [environment]::is64bitprocess
True
```

> Or does it matter as long as my OS is 64-bit?

No, it doesn't really matter. Chances are, if you don't have a 10 y/o machine, your CPU is gonna be 64-bit, and you should probably download and run the 64-bit binary. But you can also run 32-bit programs on a 64-bit CPU and OS.
