### ISSUE TITLE
Version String Parsing Suggestion

### ISSUE THREAD

**Issue by Some-Dood** [electron/rcedit#76]
Just some back story to give context to this issue: I've been studying [Electron](https://github.com/electron/electron) the past few weeks, and I finally decided to package my app. I use [electron-packager](https://github.com/electron-userland/electron-packager) to build the executable until I stumbled upon an error from `rcedit.exe`. Apparently, it was `Unable to parse version string`. It took me a while to realize that the fault was in the `version` key of my app's `package.json`, which resolved to `v0.2.3-pre-alpha`.

The current algorithm for parsing version strings fails to recognize semver-compliant version strings that begin with `v`. So to fix my problem, I had to change my `version` to `0.2.3-pre-alpha`, and the app was successfully built.

Is there any reason behind disregarding the `v` in the beginning of version strings?

https://github.com/electron/rcedit/blob/452c0c3ba521b8e7c100298e50ac34985b8e538b/src/main.cc#L39-L45

**Comment by MarshallOfSound** [comment]
A prefixed `v` is not part of the official semver spec, see [Is "v1.2.3" a semantic version?](https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version)

If you want to prefix your versions with `v` then when you pass them through to packager or rcedit you need to strip that out 👍

**Comment by Some-Dood** [comment]
Oh, thank you! I really thought it was semver-compliant. Sorry for the bother! Thanks again.
