### ISSUE TITLE
What DLLs are reqired to run rcedit ?

### ISSUE THREAD

**Issue by Garrom** [electron/rcedit#84]
I really need to use rcedit under wine but it always ends with error : `0009:fixme:ver:GetCurrentPackageId (0x33fe24 (nil)): stub `
But that's alright. This error means, most of times, problem with dll. I'm not using Wine on daily basis so I have lot of things missing in Wine. Can I please have list of required DLLs so I can put them into Wine and finally make it run ?

Thanks

_Moderator's note: Edited to remove language violating the Electron Code of Conduct._

**Comment by malept** [comment]
Which version of Wine is this, and what OS are you running it under?

As far as I know, there are no extra DLLs required to run `rcedit`.

**Comment by Garrom** [comment]
@malept Ubuntu 18 LTS with XFce. I'm using wine 3.0.2. I never installed anything into wine, I'm using crossover instead but... Do i need some kind of runtime ? Like C++, .Net, DirectX, Python or anything like that ? My Wine installation is pretty much clear, untouched, you know, like fresh install.

**Comment by lee-dohm** [comment]
@Garrom your comment was edited as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Please do not interact with the project for 24 hours.** After that, please look through your open issues and edit them to ensure they're in keeping with the Code of Conduct, and we can continue the discussion here about the best way to go forward.

**Comment by Garrom** [comment]
@lee-dohm  Sorry. I was reading Contributor Covenant Code of Conduct. What you deleted is not really that insulting but that is question of perspective I guess. Nevertheless, I still need help with running rcedit under wine. It works for others. I wonder why not it does not work for me.

**Comment by Garrom** [comment]
Solved. Problem was on my side. I installed Wine in xenial but later upgraded to bionic. I was left with xenial version of Wine which was causing mayhem in DLLs. Now it works. I just uninstalled old one and installed new one.
