### ISSUE TITLE
iexpress-created exe not modified correctly

### ISSUE THREAD

**Issue by Aidolii** [electron/rcedit#86]
"The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail."

When the manifest is modified with Resource Hacker, it launches correctly. Here are the two manifests side by side:
![image](https://user-images.githubusercontent.com/37132025/59577409-44c21480-9089-11e9-97a4-cdc5288e681a.png)

**Comment by dmascord** [comment]
Hi,

I have had a look at the code, and tested the following:


`
copy rcedit.exe rcedit2.exe
rcedit.exe --set-requested-execution-level requireAdministrator rcedit2.exe
`

Opening rcedit2.exe in Resource Hacker, I can see "<requestedExecutionLevel level='requireAdministrator' uiAccess='false' />" and rcedit2.exe works fine in a Administrator level Powershell.

I do not see any error message or issue from my side, maybe the calling script is not executing the set execution level.

Cheers,

Damien

**Comment by Aidolii** [comment]
@dmascord Here, try this one. https://anonfile.com/QcC7Lezbn4/env_exe

**Comment by Aidolii** [comment]
Thanks for the fix!
