### ISSUE TITLE
VS 2019 builds not working - 32bit and 64 bit

### ISSUE THREAD

**Issue by pavankanth6** [electron/rcedit#89]
When built using VS 2019 (MSVC v142), the rcedit.exe file that gets generated fails to set property or get property. I get standard error:

```Fatal error: Unable to get version string```

There is no verbose logging option to provide more details nor a log file that is telling me the reason. 

The command I tested with is on itself
``` rcedit.exe rcedit.exe --get-version-string "property" ```

**Comment by spiff123** [comment]
Have you tried not to execute on the in this moment running "rcedit" executable. If i copy rcedit for this test before to e.g. test.exe everything works fine for me.
