### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by HerobrinePlayer** [electron/rcedit#93]
I go this error with gyp installed it ubuntu terminal

"herobrine@DESKTOP-9JAUMFO:/mnt/c/Users/hente/Desktop/rcedit$ gyp rcedit.gyp --depth ."
"gyp: name 'MSVS_VERSION' is not defined while evaluating condition 'MSVS_VERSION=="2015"' in rcedit.gyp"

**Comment by malept** [comment]
As far as I know, this cannot be built on non-Windows platforms.
