### ISSUE TITLE
rcedit.exe fails often in python and windows bat script.

### ISSUE THREAD

**Issue by avencherus** [electron/rcedit#95]
In both the 32-bit and 64-bit versions I get this vague error.

> rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes

It has worked a couple of times, but usually it doesn't when I try to execute it with a bat script or a python script somewhat like the following:

I don't have an anti-virus running during this, like a solution in another thread I've read elsewhere.  Any other possible culprits or causes?

```
path_to_rce     = <your param here>
path_to_exe     = <your param here>
path_to_ico     = <your param here>
file_version    = <your param here>
product_version = <your param here>
company_name    = <your param here>
product_name    = <your param here>
description     = <your param here>
copyright       = <your param here>
trademarks      = <your param here>


rc_args = [

	path_to_rce,
	path_to_exe,
	"--set-icon", path_to_ico,
	"--set-file-version", '"' + file_version + '"',
	"--set-product-version", '"' + product_version + '"',
	"--set-version-string", "CompanyName", company_name,
	"--set-version-string", "ProductName", product_name,
	"--set-version-string", "FileDescription", description,
	"--set-version-string", "LegalCopyright", copyright,
	"--set-version-string", "LegalTrademarks", trademarks
]


p = Popen(rc_args, stdout=PIPE, stderr=STDOUT, shell=True)

while True:

	output = p.stdout.readline().decode('ascii')

	if output == '' and p.poll() is not None:
		break

	if output:	
		print(output.strip())


print(p.poll())
```

**Comment by rliebscher** [comment]
I got this error message when I have the exe file still running.
Maybe check with the task manager if it is running.

**Comment by avencherus** [comment]
The rcedit.exe or the exe it's trying to modify?

**Comment by rliebscher** [comment]
The exe which you try to modify. When it is running, you can't change its file.Am 14.04.20, 17:51 schrieb avencherus <notifications@github.com>:

   
  The rcedit.exe or the exe it's trying to modify?

**Comment by avencherus** [comment]
Thanks for the suggestion.

I have come back to trying to automate this, and haven't been able to reproduce the problem.  It must of been some kind of lock, though perhaps something from something else in the older versions of my build scripts.  Maybe it wasn't being released by the python process itself.

It wasn't likely to be manually run, since the executable it was modifying wasn't something directly runnable without supporting data for it to read.  It will just close itself when trying to run it in isolation.

Seems resolved on its own.  The original culprit remains a mystery.
