### ISSUE TITLE
Fatal error: Unable to set icon

### ISSUE THREAD

**Issue by TylerLeonhardt** [electron/rcedit#98]
There's not much to go off of here but take a look at the failing build here:

https://dev.azure.com/powershell/PowerShellEditorServices/_build/results?buildId=56398&view=logs&j=5aed7330-0c52-5e0f-84aa-a17a2c59b4c4&t=cfd2a6ef-3cae-5fa0-f3aa-09518df55541&l=18

We run:
```
~/.rcedit/rcedit-x64.exe $Destination\pwsh.exe --set-icon $Destination\assets\Powershell_avatar.ico
```

In our install-powershell.ps1 script here:
https://github.com/PowerShell/PowerShell/blob/97cef1df61690f5405904896a173e829c06c305b/tools/install-powershell.ps1#L425-L435

This might be a CI only failure. Is there some why I can provide more info?

**Comment by malept** [comment]
Not seeing rcedit or icon in your logs...

**Comment by TylerLeonhardt** [comment]
@malept can you elaborate? The build log shows:

"Fatal error: Unable to set icon"

which appears to be an [rcedit error message](https://github.com/electron/rcedit/blob/3a8e8239daade0c1cecffed75246ccfcca72103c/src/main.cc#L120)

**Comment by malept** [comment]
I'm looking via mobile and couldn't see any references to rcedit or icon.

**Comment by TylerLeonhardt** [comment]
In the build? It's here:

![Screenshot_20200630-173259.jpg](https://user-images.githubusercontent.com/2644648/86189922-c7343f80-baf7-11ea-83e3-df67155ee73c.jpg)

In the code? Line 425-435.

I might be misunderstanding what you're saying though.

**Comment by TylerLeonhardt** [comment]
It turns out our ico file was not on the file system... oops.

Can I turn this issue into an ask to make the error message better?

**Comment by malept** [comment]
I can't reproduce this:

```
rcedit-x64.exe electron.exe --set-icon nonexistent.ico

Cannot open file 'nonexistent.ico'
Fatal error: Unable to set icon
```
